### ISSUE TITLE
sci-libs/tensorflow: respect EPREFIX

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#861]
Tensorflow does not link o Gentoo-Prefix because it links is system-wide glibc instead of the one from `${EPREFIX}/usr/lib64`.

```
Server crashed during startup. Now printing '/apps/gentoo/var/tmp/portage/dev-util/bazel-0.10.1/homedir/.cache/bazel/_bazel_mmokrejs/e3df78874bad6094af808df865f06e36/server/jvm.out':
JNI initialization failed: /apps/gentoo/var/tmp/portage/dev-util/bazel-0.10.1/homedir/.cache/bazel/_bazel_mmokrejs/install/7ad79e7531146c0e1240a750b0a3ea91/_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /apps/gentoo/var/tmp/portage/dev-util/bazel-0.10.1/homedir/.cache/bazel/_bazel_mmokrejs/install/7ad79e7531146c0e1240a750b0a3ea91/_embedded_binaries/libunix.so).  Possibly your installation has been corrupted.
java.lang.UnsatisfiedLinkError: /apps/gentoo/var/tmp/portage/dev-util/bazel-0.10.1/homedir/.cache/bazel/_bazel_mmokrejs/install/7ad79e7531146c0e1240a750b0a3ea91/_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /apps/gentoo/var/tmp/portage/dev-util/bazel-0.10.1/homedir/.cache/bazel/_bazel_mmokrejs/install/7ad79e7531146c0e1240a750b0a3ea91/_embedded_binaries/libunix.so)
```

[build.log.txt](https://github.com/gentoo/sci/files/1902671/build.log.txt)

**Comment by markwright** [comment]
I set CPPFLAGS, LDFLAGS and CXXFLAGS in the tensorflow-1.8.0.ebuild, hopefully that should fix it on EPREFIX.  It would be neat if you test it please and let us know if it works or not.

**Comment by mmokrejs** [comment]
Isn't tha a `bazel` issue?

`/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /apps/gentoo/var/tmp/portage/dev-util/bazel-0.10.1/homedir/.cache/bazel/_bazel_mmokrejs/install/7ad79e7531146c0e1240a750b0a3ea91/_embedded_binaries/libunix.so)`

I will try nevertheless.

**Comment by mmokrejs** [comment]
Still does not work.  [build.log.txt](https://github.com/gentoo/sci/files/1970019/build.log.txt)

**Comment by TheChymera** [comment]
tensorflow is now being distributed via `::gentoo`.
