### ISSUE TITLE
sci-biology/ugene: remove old ebuilds requiring qt4 eclass

### ISSUE THREAD

**Issue by progenyx** [gentoo/sci#877]
Gentoo has dropped the qt4-r2 eclass which creates annoying errors for older, no longer installed versions of the software.

**Comment by Kagami** [comment]
Also:

```
$cd /var/lib/layman/science
$ grep -l -r qt4-r2 .
./media-gfx/librecad/librecad-1.0.3.ebuild
./media-gfx/librecad/librecad-1.0.4.ebuild
./media-gfx/librecad/librecad-2.0.7.ebuild
./sci-biology/ngsview/ngsview-0.91.ebuild
./sci-biology/ugene/ugene-1.13.3.ebuild
./sci-biology/ugene/ugene-1.16.1.ebuild
./sci-misc/elmer-gui/elmer-gui-9999.ebuild
```

**Comment by Kagami** [comment]
Fixed in master.

**Comment by heroxbd** [comment]
Thanks!

**Comment by blade2005** [comment]
https://gitweb.gentoo.org/proj/sci.git/tree/sci-misc/elmer-gui/elmer-gui-9999.ebuild

It looks like this was not completely fixed. I'm still getting this on elmer-gui @heroxbd
